### ISSUE TITLE
Clarify maintenance status

### ISSUE THREAD

**Issue by djc** [yoshuawuyts/futures-time#10]
Is this crate being maintained? Given the fact that the last release was published almost 2 years ago and there haven't been substantial commits since then -- notably, no bump to later versions of its own dependencies, it might be good to proactively clarify if the maintainer(s) are no longer interested in keeping this up to date going forward.

**Comment by yoshuawuyts** [comment]
If any issues come up we'll resolve them; I wouldn't say it's not maintained insofar that it's not needed much maintenance. I might actually bump this again soon to add platform support for WASI 0.2, which should be stable I believe in ~April.
